// This code was generated by a vsSolutionBuildEvent. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
namespace net.r_eg.EvMSBuild
{
    using System;

    public struct EvMSBuildVersion
    {
        public static readonly Version number = new Version(S_NUM_REV);

        public const string S_NUM = "1.14.1";
        public const string S_REV = "0";

        public const string S_NUM_REV = S_NUM + "." + S_REV;

        public const string B_SHA1 = "";

        internal const string S_PRODUCT = S_NUM_REV + "";
        internal const string S_INFO    = S_PRODUCT + "+" + B_SHA1;
    }
}